test.yml log added

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,7 +7,6 @@ on:
     branches: [ "main" ]
 
 jobs:
-
   test:
     runs-on: ubuntu-latest
 
@@ -34,9 +33,6 @@ jobs:
       with:
         go-version: '1.21.1'
 
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v3
-
     - name: Install golang-migrate
       run: |
         curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
@@ -44,7 +40,8 @@ jobs:
         which migrate
 
     - name: Run migrations
-      run: make migrateup
+      run: |
+        make migrateup || echo "Migration failed. See output above for details."
 
     - name: Test
       run: make test
